version: "3"
services:
  test:
   image: mysql:5
   tmpfs:
     - /var/lib/mysql
   ports: 
    - 23306:3306
   expose:
    - 23306
   environment:
     MYSQL_ROOT_PASSWORD: supersecret
     MYSQL_DATABASE: test
     MYSQL_USER: test
     MYSQL_PASSWORD: secret
   restart: always
   networks:
    - public
    - private
  # node:
  #   image: node:12 # https://hub.docker.com/_/node/
  #   user: node
  #   working_dir: /home/node/app
  #   environment:
  #     NODE_ENV: test
  #     DB_URL: mysql://bq:secret@db:23306/bq
  #     JWT_SECRET: xxxxxxxx
  #     ADMIN_EMAIL: admin@localhost
  #     ADMIN_PASSWORD: changeme
  #     DB_PORT: 23306
  #     DB_PASSWORD: secret
  #     DB_NAME: test
  #     DB_USER: test
  #   volumes:
  #     - ./:/home/node/app # montamos el codigo en el HOME del usuario _node_
  #   expose:
  #     - 8080 # nuestra app corre en el puerto 8080
  #   ports:
  #     # mapeamos el puerto 8080 de nuestro contenedor al puerto 80 de nuestra
  #     # máquina
  #     - 80:8080
  #   # reinstalamos las dependencias y levantamos el servidor
  #   command: bash -c 'rm -rf node_modules && npm install && npm run run:sql && npm run test:e2e'
  #   depends_on:
  #     - test
  #   networks:
  #     - public
  #     - private
networks:
  public:
    internal: false
  private:
    internal: true
