version: "3"
services:
  test:
   image: mysql:5
   tmpfs:
     - /var/lib/mysql
   ports: 
    - 23306:3306
   expose:
    - 23307
   environment:
     MYSQL_ROOT_PASSWORD: supersecret
     MYSQL_DATABASE: test
     MYSQL_USER: test
     MYSQL_PASSWORD: secret
   restart: always
   networks:
    - public
    - private
networks:
  public:
    internal: false
  private:
    internal: true
